on:
  push:
    branches:
      - main

jobs:
  display_content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read abc.txt
        id: read_abc
        run: |
          ABC_CONTENT=$(cat abc.txt)
          echo "ABC_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$ABC_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Call AI processing
        id: ai_process
        run: |
          API_ENDPOINT="https://openrouter.ai/api/v1/chat/completions"
          API_KEY="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" # Replace with your key
          MODEL_NAME="google/gemma-3-27b-it:free"

          echo "Sending to AI: $ABC_CONTENT"

          RESPONSE=$(curl -s -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $API_KEY" \
            -d "{
              \"model\": \"$MODEL_NAME\",
              \"messages\": [
                {\"role\": \"user\", \"content\": \"$ABC_CONTENT\"}
              ]
            }" \
            "$API_ENDPOINT")

          echo "Raw API Response:"
          echo "$RESPONSE"

          # Check if the response has 'choices' or 'error'
          if echo "$RESPONSE" | jq -e '.choices' > /dev/null; then
            AI_RESPONSE=$(echo "$RESPONSE" | jq -r '.choices[0].message.content // .choices[0].text // empty')

            if [ -z "$AI_RESPONSE" ]; then
              AI_RESPONSE="No response from AI"
            fi
          elif echo "$RESPONSE" | jq -e '.error' > /dev/null; then
            ERROR_MESSAGE=$(echo "$RESPONSE" | jq -r '.error.message // empty')
            AI_RESPONSE="Error from AI: $ERROR_MESSAGE"
          else
            AI_RESPONSE="Invalid API Response Structure"
          fi

          echo "AI_RESPONSE<<EOF" >> $GITHUB_ENV
          echo "$AI_RESPONSE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Output AI response
        run: |
          echo "AI Response:"
          echo "$AI_RESPONSE"
