name: Display abc.txt Content on Push

on:
  push:
    branches:
      - main

jobs:
  display_content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display abc.txt content
        run: |
          echo "Content of abc.txt:"
          cat abc.txt
