name: Send abc.txt to OpenAI API

on:
  push:
    branches:
      - main

jobs:
  send_to_ai:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read abc.txt content
        id: read_file
        run: |
          echo "Reading abc.txt..."
          ABC_CONTENT=$(cat abc.txt | tr '\n' ' ' | sed 's/"/\\"/g')
          echo "ABC_CONTENT=$ABC_CONTENT" >> $GITHUB_ENV

      - name: Send to OpenAI API
        id: call_openai
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Sending content to OpenAI..."
          RESPONSE=$(curl --fail --silent --show-error --max-time 20 https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d "{
              \"model\": \"gpt-3.5-turbo\",
              \"messages\": [
                {\"role\": \"user\", \"content\": \"$ABC_CONTENT\"}
              ]
            }")

          echo "Raw API response:"
          echo "$RESPONSE"

          # Extract the response safely
          AI_RESPONSE=$(echo "$RESPONSE" | jq -r '.choices[0].message.content // "No AI response"')
          echo "AI_RESPONSE=$AI_RESPONSE" >> $GITHUB_ENV

      - name: Show AI response
        run: |
          echo "Final AI Response:"
          echo "$AI_RESPONSE"
