name: Send abc.txt Content to AI

on:
  push:
    branches:
      - main

jobs:
  send_to_ai:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read content from abc.txt
        id: read_abc
        run: |
          # Read the content of abc.txt into a variable
          ABC_CONTENT=$(cat abc.txt)
          # Debugging: Check if content is read properly
          echo "Content from abc.txt:"
          echo "$ABC_CONTENT"
          
          # Save the content into GitHub environment variable
          echo "ABC_CONTENT=$ABC_CONTENT" >> $GITHUB_ENV

      - name: Call AI API
        id: ai_process
        run: |
          # Set the API key for OpenAI (You should store this in GitHub Secrets for security)
          API_KEY="${{ secrets.OPENAI_API_KEY }}"

          # Debugging: Print out what we are sending to AI
          echo "Sending to AI: $ABC_CONTENT"
          
          # Make the POST request to the OpenAI API
          RESPONSE=$(curl -s -X POST "https://api.openai.com/v1/completions" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $API_KEY" \
            -d '{
              "model": "text-davinci-003",
              "prompt": "'"$ABC_CONTENT"'",
              "max_tokens": 150
            }')

          # Extract the AI response
          AI_RESPONSE=$(echo "$RESPONSE" | jq -r '.choices[0].text // empty')

          if [ -z "$AI_RESPONSE" ]; then
            AI_RESPONSE="No response from AI"
          fi

          # Output the response
          echo "AI Response: $AI_RESPONSE"
          echo "AI_RESPONSE=$AI_RESPONSE" >> $GITHUB_ENV

      - name: Output AI response
        run: |
          # Output the response for debugging
          echo "AI Response from AI API:"
          echo "$AI_RESPONSE"
