name: Sync abc.txt to hello.txt

on:
  push:
    paths:
      - abc.txt

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy abc.txt to hello.txt
      run: cp abc.txt hello.txt

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add hello.txt
        git commit -m "Sync: Copied abc.txt to hello.txt" || echo "No changes to commit"
        git push
